const targetDiv = document.getElementById("targetDiv");
   targetDiv.style.backgroundColor = "yellow";
   targetDiv.style.color= "blue";
   targetDiv.style.margin = "30px";
   targetDiv.style.padding = "20px";
   targetDiv.style.fontSize = "30px";
   targetDiv.style.fontWeight = "bold";
   targetDiv.style.height = "300px";
   targetDiv.style.width = "450px";